name: Deploy Apps Script
description: Deploy Google Apps Script from GitHub repository
author: "Kseymur (https://github.com/Kseymur)"
inputs:
  script_id:
    description: The Apps Script project ID
    required: true
  src_folder:
    description: Folder containing script files
    required: true
env:
  CLIENT_ID:
    description: OAuth2 client ID
    required: true
  CLIENT_SECRET:
    description: OAuth2 client secret
    required: true
  REFRESH_TOKEN:
    description: OAuth2 refresh token
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Run main script
      run: node dist/index.js
      env:
        CLIENT_ID: ${{ env.CLIENT_ID }}
        CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ env.REFRESH_TOKEN }}
      with:
        script_id: ${{ inputs.script_id }}
        src_folder: ${{ inputs.src_folder }}