name: Deploy Apps Script
description: Deploy Google Apps Script from GitHub repository
author: "Kseymur (https://github.com/Kseymur)"
inputs:
  script_id:
    description: The Apps Script project ID
    required: true
  src_folder:
    description: Folder containing script files
    required: true
env:
  CLIENT_ID:
    description: The OAuth2 client ID
    required: true
  CLIENT_SECRET:
    description: The OAuth2 client secret
    required: true
  REFRESH_TOKEN:
    description: The OAuth2 refresh token
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.workspace }} 

    - name: Build TypeScript
      run: npm run build
      shell: bash
      working-directory: ${{ github.workspace }} 

    - name: Run main script
      run: node dist/index.js "${{ inputs.script_id }}" "${{ inputs.src_folder }}"
      shell: bash
      env:
        CLIENT_ID: ${{ env.CLIENT_ID }}
        CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ env.REFRESH_TOKEN }}
      working-directory: ${{ github.workspace }}  